version: '3.8'

services:
  doom:
    build: .
    container_name: doom-game
    ports:
      - "8080:8080"
    environment:
      - DISPLAY=:99
    volumes:
      - doom-saves:/games/doom
    restart: unless-stopped
    labels:
      - "com.example.description=Doom Game Container"
      - "com.example.version=1.0"

volumes:
  doom-saves:
    driver: local 