#!/bin/bash

echo "🎮 Doom Download Helper"
echo "======================"
echo ""
echo "📥 To get Doom files, please:"
echo ""
echo "1. Open your web browser"
echo "2. Go to: https://www.doomworld.com/classicdoom/info/shareware.php"
echo "3. Click on 'doom19s.zip' to download"
echo "4. Extract the zip file"
echo "5. Copy DOOM.EXE and DOOM1.WAD to this directory:"
echo "   $(pwd)/doom/"
echo ""
echo "📁 Creating doom directory..."
mkdir -p doom
echo "✅ Doom directory created at: $(pwd)/doom/"
echo ""
echo "🔄 After you copy the files, run:"
echo "   docker run -it --rm -v \$(pwd)/doom:/games/doom doom-simple"
echo ""
echo "🎯 Note: You'll need a graphical interface to see the game."
echo "   The container will work, but you won't see the game window"
echo "   in a terminal-only environment." 